#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          smallPropeller, tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          bigPropeller,  tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorC,          syringe,       tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorD,           ,             tmotorEV3_Large, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

}

int pumpSyringe() {
	// sucks in water
	setMotorSpeed(syringe, -1000);
	sleep(10000);

	// sucks out water
	setMotorSpeed(syringe, 1000);
	sleep(10000);
}
