#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color)
#pragma config(Motor,  motorA,          bigPropeller,  tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          smallPropeller, tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorC,          syringe,       tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorD,          LED,           tmotorEV3_Large, PIDControl)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	// propellers
	setMotorSpeed(bigPropeller, 1000);
	setMotorSpeed(smallPropeller, 1000);
	sleep(2000);

	// color sensor
	//setSoundVolume(50);

	// when it hits the coral underwater
	//int threshold = 10;
	//int lightVal;
	//while(true){
	//	lightVal = SensorValue(S3);
	//	displayBigTextLine(3, "val: %d", lightVal);

	//	if(lightVal < threshold){ // darker
	//		// beep here
	//		playTone(700, 10);
	//	}else{ // lighter
	//		setMotorSpeed(motorD, 100);
	//	}

	//}

	// syringe code
	//// sucks in water
	//setMotorSpeed(syringe, -10000);
	//sleep(20000);

	//// sucks out water
	//setMotorSpeed(syringe, 10000);
	//sleep(20000);



}
